
import 'package:grameern_communication/model/medicine_model.dart';

List<Medicine> medicineList=[
    Medicine(1,'Ecospirin 150Mg Tablet 14’S', 'ACME Limited', 7.50, 8.43, 0,false , 'assets/napa_image.png', 'Napa is indicated for fever, common cold and influenza, headache, toothache, earache, body pain, myalgia, neuralgia, dysmenorrhoea, sprains, colic pain, back pain, post-operative pain, postpartum pain, inflammatory pain, and post-vaccination pain in children. It is also indicated for rheumatic & osteoarthritic pain and stiffness of joints.'),
    Medicine(2,'Napa 150mg', 'Square Limited', 10.50, 23.43, 0,false , 'assets/napa_image.png', 'Napa is indicated for fever, common cold and influenza, headache, toothache, earache, body pain, myalgia, neuralgia, dysmenorrhoea, sprains, colic pain, back pain, post-operative pain, postpartum pain, inflammatory pain, and post-vaccination pain in children. It is also indicated for rheumatic & osteoarthritic pain and stiffness of joints.'),
    Medicine(3,'Asthalin Inhaler 200Md', 'ACME Limited', 20.50, 34.43, 0,false , 'assets/napa_image.png', 'Napa is indicated for fever, common cold and influenza, headache, toothache, earache, body pain, myalgia, neuralgia, dysmenorrhoea, sprains, colic pain, back pain, post-operative pain, postpartum pain, inflammatory pain, and post-vaccination pain in children. It is also indicated for rheumatic & osteoarthritic pain and stiffness of joints.'),
    Medicine(4,'Levothyroxine  150Mg Tablet 14’S', 'ACME Limited', 45.50, 48.43, 0,false , 'assets/napa_image.png', 'Napa is indicated for fever, common cold and influenza, headache, toothache, earache, body pain, myalgia, neuralgia, dysmenorrhoea, sprains, colic pain, back pain, post-operative pain, postpartum pain, inflammatory pain, and post-vaccination pain in children. It is also indicated for rheumatic & osteoarthritic pain and stiffness of joints.'),
    Medicine(5,'Atorvastatin  150Mg Tablet 14’S', 'ACME Limited', 12.50, 8.43, 0,false , 'assets/napa_image.png', 'Napa is indicated for fever, common cold and influenza, headache, toothache, earache, body pain, myalgia, neuralgia, dysmenorrhoea, sprains, colic pain, back pain, post-operative pain, postpartum pain, inflammatory pain, and post-vaccination pain in children. It is also indicated for rheumatic & osteoarthritic pain and stiffness of joints.'),
    Medicine(6,'Metformin  150Mg Tablet 14’S', 'ACME Limited', 56.50, 48.43, 0,false , 'assets/napa_image.png', 'Napa is indicated for fever, common cold and influenza, headache, toothache, earache, body pain, myalgia, neuralgia, dysmenorrhoea, sprains, colic pain, back pain, post-operative pain, postpartum pain, inflammatory pain, and post-vaccination pain in children. It is also indicated for rheumatic & osteoarthritic pain and stiffness of joints.'),
    Medicine(7,'Omeprazole 150Mg Tablet 14’S', 'ACME Limited', 75.50, 88.43, 0,false , 'assets/napa_image.png', 'Napa is indicated for fever, common cold and influenza, headache, toothache, earache, body pain, myalgia, neuralgia, dysmenorrhoea, sprains, colic pain, back pain, post-operative pain, postpartum pain, inflammatory pain, and post-vaccination pain in children. It is also indicated for rheumatic & osteoarthritic pain and stiffness of joints.'),
];

